---

- name: Install Apache
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: false
  with_items:
    - apache2
    - libapache2-mod-fcgid
  become: true
  become_user: root
  tags:
    - apache2-fcgi
