---

- name: Update and upgrade all APT packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # One day
    install_recommends: false
  become: true
  become_user: root
  tags:
    - update-packages
    - update-packages-ubuntu

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
    install_recommends: false
  become: true
  become_user: root
  tags:
    - update-packages
    - update-packages-ubuntu

- name: Autoremove APT packages
  apt:
    autoremove: yes
    install_recommends: false
  become: true
  become_user: root
  tags:
    - update-packages
    - update-packages-ubuntu
