---

- name: Update Homebrew
  homebrew:
    update_homebrew: yes
  tags:
    - update-packages
    - update-packages-macosx

- name: Upgrade dependencies for Graphviz
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    - fontconfig
    - freetype
    - gd
    - pcre
    - perl
    - pkg-config
    - python
    - ruby
    - swig
    - webp
  tags:
    - update-packages
    - update-packages-macosx
