- name: Include variables
  include_vars: ../vars/main-{{ ansible_distribution }}.yml
  tags:
    - pam-limits

- name: Include variables
  include: main-{{ ansible_distribution }}.yml
  tags:
    - pam-limits
