---

- name: Test if hook source is executable
  stat:
    path: "{{ git_precommit_hook_source }}"
  register: hook_source_stat
  tags:
    - git-hooks

- name: Ensure that hook source is executable
  assert:
    that:
      - "hook_source_stat.stat.executable"
  tags:
    - git-hooks

- name: Symlink Git pre-commit hook
  file:
    src: "{{ git_precommit_hook_source }}"
    dest: "{{ git_precommit_hook_target }}"
    mode: 0755
    state: link
  become: true
  become_user: "{{ mediacloud_user }}"
  tags:
    - git-hooks
